version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: infra/ruby/Dockerfile
    working_dir: /src
    tty: true
    volumes:
      - ./src:/src
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
#   db:
#     build:
#       context: .
#       dockerfile: infra/db/Dockerfile
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
#     ports:
#       - "5432:5432"
#     volumes:
#       - db-data:/var/lib/postgresql/data
#   pgadmin:
#     image: dpage/pgadmin4:6.11
#     container_name: container_pgadmin
#     ports:
#       - 8080:80
#     volumes:
#       - volume_pgadmin:/var/lib/pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: example@example.com
#       PGADMIN_DEFAULT_PASSWORD: password
#     depends_on:
#       - db

# volumes:
#   db-data:
#   volume_pgadmin:
