version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: infra/python/Dockerfile
    working_dir: /src
    tty: true
    volumes:
      - ./src:/src
    ports:
      - "8080:8080"
